// <auto-generated />
namespace MVCAppDemoWithAuthtentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewPropertyaddedfornameinmembershiptype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewPropertyaddedfornameinmembershiptype));
        
        string IMigrationMetadata.Id
        {
            get { return "202008210643395_New Property added for name in membership type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
