// <auto-generated />
namespace MVCAppDemoWithAuthtentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewMovietypeisaddedforgenretype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMovietypeisaddedforgenretype));
        
        string IMigrationMetadata.Id
        {
            get { return "202008210435131_New Movie type is added for genre type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
